---
- name: Retrieve catalog request sysid
  servicenow.itsm.api_info:
    resource: sc_request
    sysparm_query: numberSTARTSWITH{{ ticket_number }}
  register: requestresult
  when: ticket_number != ''

- name: Update a catalog work notes and state in ServiceNow
  servicenow.itsm.api:
    action: patch
    resource: sc_request
    sys_id: "{{ requestresult.record[0].sys_id }}"
    data:
      request_state: "{{ request_state | default(omit) }}"
      work_notes: "{{ work_notes }}"
  when:
    - ticket_number != ''
    - requestresult.record[0].sys_id is defined

# Worknotes if you want to provide a summary of a large log set. <pre> specifically is used for code
# [code]
# <details>
#     <summary>Click to show</summary>
#     <pre>
#     </pre>
# </details>
# [/code]
