collections:

  - name: servicenow.servicenow
    source: https://towerpah.shadowman.dev/api/galaxy/content/community/

  - name: community.general
    source: https://towerpah.shadowman.dev/api/galaxy/content/community/

  - name: servicenow.itsm